# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20160616_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome_empresa',
            new_name='areas_de_interesse',
        ),
        migrations.AddField(
            model_name='perfil',
            name='projetos_de_pesquisa',
            field=models.CharField(default='Ferramentas de gerenciamento', max_length=255),
            preserve_default=False,
        ),
    ]
