# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20160616_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conviteobserver',
            name='convite',
        ),
        migrations.RemoveField(
            model_name='conviteobserver',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='observer',
        ),
        migrations.DeleteModel(
            name='ConviteObserver',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
