# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_auto_20160616_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='areas_de_interesse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='projetos_de_pesquisa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
